name:                RosettaParser
version:             0.1.0.0
github:              "macocianradu/RosettaParser"
license:             BSD3
author:              "Adrian Radu Macocian"
maintainer:          "rmacocian@gmail.com"
copyright:           "2021 Adrian Radu Macocian"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/macocianradu/RosettaParser#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- time
- mtl
- prettyprinter
- parser-combinators
- text
- filepath
- directory

library:
  source-dirs: src

executables:
  RosettaParser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RosettaParser
    when:
    - condition: false
      other-modules: Paths_RosettaParser

tests:
  RosettaParser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RosettaParser
    - hspec-megaparsec
    - hspec